### ISSUE TITLE
“ivy-omni-org--bookmarks” breaks if a bookmark has no associated filename

### ISSUE THREAD

**Issue by TinaRussell** [akirak/ivy-omni-org#2]
```
(defun ivy-omni-org--bookmarks ()
  "Get a list of Org bookmarks."
  (bookmark-maybe-load-default-file)
  (cl-remove-if-not (lambda (info)
                      (let ((filename (alist-get 'filename (cdr info))))
                        (string-match-p "\\.org\\'" filename)))
                    bookmark-alist))
```
If any bookmark in `bookmark-alist` does not have an associated filename (a web bookmark, for instance), `string-match-p` will choke, complaining that nil is not a string. This will result in `ivy-omni-org` failing with a “Wrong type argument: stringp, nil” error.
The solution is to replace the `filename` argument to `string-match-p` with `(or filename "")`.

**Comment by akirak** [comment]
Thanks for reporting this issue.

I've applied a fix onto `fix/bookmark-non-filename` branch. Could you please test if it works?

**Comment by TinaRussell** [comment]
Yes, it works!

**Comment by akirak** [comment]
Thanks. I've merged it into master.
